<?xml version="1.0" encoding="UTF-8"?>
<definitions name="BilleteraService"
    targetNamespace="urn:localhost"
    xmlns:tns="urn:localhost"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns="http://schemas.xmlsoap.org/wsdl/">

    <!-- Tipos comunes para Item y Map -->
    <types>
        <xsd:schema targetNamespace="urn:localhost">
            <!-- Definición del tipo Item -->
            <xsd:complexType name="Item">
                <xsd:sequence>
                    <xsd:element name="key" type="xsd:string"/>
                    <xsd:element name="value" type="xsd:string"/>
                </xsd:sequence>
            </xsd:complexType>

            <!-- Definición de la colección de Items -->
            <xsd:complexType name="ItemArray">
                <xsd:sequence>
                    <xsd:element name="item" type="tns:Item" minOccurs="0" maxOccurs="unbounded"/>
                </xsd:sequence>
            </xsd:complexType>

            <!-- Definición del tipo Map (para respuesta) -->
            <xsd:complexType name="Map">
                <xsd:sequence>
                    <xsd:element name="item" minOccurs="0" maxOccurs="unbounded">
                        <xsd:complexType>
                            <xsd:sequence>
                                <xsd:element name="key" type="xsd:string"/>
                                <xsd:element name="value" type="xsd:string"/>
                            </xsd:sequence>
                        </xsd:complexType>
                    </xsd:element>
                </xsd:sequence>
            </xsd:complexType>

            <!-- Definición para la respuesta-->
            <xsd:complexType name="MapResponse">
                <xsd:sequence>
                    <xsd:element name="success" type="xsd:boolean"/>
                    <xsd:element name="cod_error" type="xsd:string"/>
                    <xsd:element name="message_error" type="xsd:string"/>
                    <xsd:element name="data" type="tns:Map"/>
                </xsd:sequence>
            </xsd:complexType>
        </xsd:schema>
    </types>

    <!-- Mensajes para registrarCliente -->
    <message name="registrarClienteRequest">
        <part name="data" type="tns:ItemArray"/>
    </message>
    <message name="registrarClienteResponse">
        <part name="return" type="tns:MapResponse"/>
    </message>

    <!-- Mensajes para loginCliente -->
    <message name="loginClienteRequest">
        <part name="data" type="tns:ItemArray"/>
    </message>
    <message name="loginClienteResponse">
        <part name="return" type="tns:MapResponse"/>
    </message>

    <!-- Definición del puerto y operaciones -->
    <portType name="BilleteraPortType">
        <!-- Operación para registrarCliente -->
        <operation name="registrarCliente">
            <input message="tns:registrarClienteRequest"/>
            <output message="tns:registrarClienteResponse"/>
        </operation>

         <!-- Operación para loginCliente -->
        <operation name="loginCliente">
            <input message="tns:loginClienteRequest"/>
            <output message="tns:loginClienteResponse"/>
        </operation>
    </portType>

    <!-- Enlace para las operaciones -->
    <binding name="BilleteraBinding" type="tns:BilleteraPortType">
        <soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
        
        <!-- Operación para registrarCliente -->
        <operation name="registrarCliente">
            <soap:operation soapAction="urn:localhost#registrarCliente"/>
            <input>
                <soap:body use="literal" namespace="urn:localhost" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
            </input>
            <output>
                <soap:body use="literal" namespace="urn:localhost" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
            </output>
        </operation>

        <!-- Operación para loginCliente -->
        <operation name="loginCliente">
            <soap:operation soapAction="urn:localhost#loginCliente"/>
            <input>
                <soap:body use="literal" namespace="urn:localhost" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
            </input>
            <output>
                <soap:body use="literal" namespace="urn:localhost" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
            </output>
        </operation>
    </binding>

    <!-- Servicio -->
    <service name="BilleteraService">
        <port name="BilleteraPort" binding="tns:BilleteraBinding">
            <soap:address location="http://localhost:8000/soap/cliente"/>
        </port>
    </service>

</definitions>
